export const FETCH_ALL_COUNTRIES = "FETCH_ALL_COUNTRIES";
export const FETCH_COUNTRIES_BY_REGION = "FETCH_COUNTRIES_BY_REGION";
export const FETCH_COUNTRIES_BY_NAME = "FETCH_COUNTRIES_BY_NAME";
export const SET_COUNTRIES_TO_DISPLAY = "SET_COUNTRIES_TO_DISPLAY";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SET_LOADING = "SET_LOADING";
