export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const SET_CURRENT_COUNTRIES = "SET_CURRENT_COUNTRIES";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_LOADING = "SET_LOADING";

export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
